[package]
name = "sky130"
version = "0.1.0"
edition = "2021"

[dependencies]
rivet = { version = "0.1.0", path = "../../rivet" }
cadence = { version = "0.1.0", path = "../../cadence" }
indoc = "2"
rust_decimal = "1"
rust_decimal_macros = "1"
