[package]
name = "sky130"
version = "0.1.0"
edition = "2021"

[dependencies]
rivet = { version = "0.1.0", path = "../../rivet" }
genus = { version = "0.1.0", path = "../../tools/genus" }
innovus = { version = "0.1.0", path = "../../tools/innovus" }
indoc = "2"
