[workspace]

resolver = "2"
members = [
    "examples/decoder",
    "rivet",
    "pdks/sky130",
    "tools/genus",
    "tools/innovus",
    "tools/chipyard",
    "tools/pegasus", "cadence", "flows/sky130_cadence",
]
