[package]
name = "decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
rivet = { version = "0.1.0", path = "../../rivet" }
sky130 = { version = "0.1.0", path = "../../pdks/sky130" }
clap = { version = "4", features = ["derive"] }
toml = "0.8"
